# Generated by Django 5.2.1 on 2025-06-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_category_creativecontent_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="creativecontent",
            name="comments_count",
            field=models.PositiveIntegerField(default=0, verbose_name="评论数"),
        ),
    ]
